export const IPC = {
  IMPORT_FILE: 'import-file',
  PARSE_FILE: 'parse-file',
  INGEST_JSON: 'ingest-json',
  LOAD_BANKS: 'load-banks',
  LOAD_QUESTIONS: 'load-questions',
  DELETE_BANK: 'delete-bank',
  CREATE_ATTEMPT: 'create-attempt',
  SAVE_RESPONSE: 'save-response',
  COMPLETE_ATTEMPT: 'complete-attempt',
  GET_HISTORY: 'get-history',
  GET_RESPONSES: 'get-responses',
  OPEN_PANEL: 'open-panel',
  SET_AI_SERVICE: 'set-ai-service',
  CLOSE_PANEL: 'close-panel',
  GENERATE_PROMPT: 'generate-prompt',
  COPY_TO_CLIPBOARD: 'copy-to-clipboard',
  PANEL_STATE_CHANGED: 'panel-state-changed',
  EXPORT_BANK: 'export-bank',
  SAVE_GENERATED_JSON: 'save-generated-json',
  RESIZE_PANEL: 'resize-panel',
  GET_WATERFALL_PROGRESS: 'get-waterfall-progress',
  ADVANCE_WATERFALL: 'advance-waterfall',
  GET_ACTIVE_ATTEMPT: 'get-active-attempt',
  DELETE_ATTEMPT: 'delete-attempt',
  UPDATE_RESPONSE: 'update-response',
  UPDATE_QUESTION: 'update-question',
} as const;
